/*
 * cal_conf.h - CANopen Library Configuration
 *
 * Copyright (C) 1998-2026  by port GmbH  Halle/Saale Germany
 *
 *------------------------------------------------------------
 * This file was generated by the Industrial Communication Creator
 * with CANopen feature V7.0.0.202112202107
 * from project C:\Work\Repos\canopenio_stm32h7\src\application\obj_dic\application.iccproj
 * on 2026/05/29 at 10:24:52.
 */

/**
 * \file cal_conf.h
 * \brief CANopen Library configuration
 *
 * This module contains the configuration
 * of the CANopen Library for the CANopen device.
 *
 * \author port GmbH  Halle/Saale Germany
 */



#ifndef CAL_CONF_H
#define CAL_CONF_H	1
#define CO_CONFIG_ICCTOOL_VERSION 0x00070000

/* active configuration : 0 */
#define CO_CONFIG_USE_TARGET_0 1


/*
 * General Settings
 */
#define CONFIG_CAN_ERROR_HANDLING           	1
#define CONFIG_CONST_OBJDIR                 	1
#define CONFIG_EXTERN_COMMUNICATION_PARAMETER	1
#define CONFIG_FAST_SORT                    	1
#define CONFIG_LARGE_TIMER                  	1
#define CONFIG_SLAVE                        	1
#define CO_DT_INIT_VAR                      	
#define CO_LIB_INIT_VAR                     	
#define CO_LIB_UNINIT_VAR                   	
#define CONFIG_CAN_OBJECTS                  	18


 /*
 * General Line Settings
 */
#define CONFIG_SYNC_CONSUMER                	1
#define CONFIG_CO_LED                       	1
#define CONFIG_CO_RUN_LED                   	1
#define CONFIG_CO_ERR_LED                   	1

/*
 * CANopen Services
 */
#define CONFIG_PDO_EVENTTIMER               	1
#define CONFIG_SDO_SERVER                   	1
#define CONFIG_FLOAT_VALUES                 	1
#define CONFIG_SEG_SDO                      	1
#define CONFIG_PDO_CONSUMER                 	3
#define CONFIG_PDO_PRODUCER                 	9
#define CONFIG_NON_VOLATILE_MEM             	1
#define CONFIG_MAPPING_CNT                  	30
#define CONFIG_RPDO_MAPPING_CNT             	7
#define CONFIG_TPDO_MAPPING_CNT             	23
#define CONFIG_HEARTBEAT_PRODUCER           	1
#define CONFIG_EMCY_PRODUCER                	1

/*
 * NMT Service Settings
 */

/*
 * SDO Service Settings
 */
#define CONFIG_LIMITS_CHECK                 	1

/*
 * PDO Service Settings
 */
#define CONFIG_PDO_RTR_IND                  	1

/*
 * SYNC Service Settings
 */

 /*
 * Application Layer Settings
 */


/*
 * Hardware configuration 0: 0
 */


/*
 * Code Maturity Level Options
 */



/*
 * CPU Setup
 */
#ifdef CO_CONFIG_USE_TARGET_0
#define CONFIG_COLIB_TIMER                  	1
#define CONFIG_CPU_FAMILY_STM32_H7          	1
#define CONFIG_CPU_TYPE_STM32H743           	1
#define CONFIG_TIMER_INC                    	10

#ifdef DEF_HW_PART
#include <cpu_stm32_h7.h>
#endif /* DEF_HW_PART */

#endif /* CO_CONFIG_USE_TARGET_0*/


/*
 * CAN Controller Setup
 */
#ifdef CO_CONFIG_USE_TARGET_0
#define CONFIG_CAN_FAMILY_FDCAN             	1
#define CONFIG_COLIB_BUFFER                 	1
#define CONFIG_TX_BUFFER_SIZE               	10
#define CONFIG_RX_BUFFER_SIZE               	10
#define CONFIG_COLIB_FLUSHMBOX              	1
#define CONFIG_FLUSHMBOX_READ_MAXMSG        	10

#define CONFIG_CAN_START_TYPE               	1
#define CONFIG_STANDARD_IDENTIFIER          	1
#define CONFIG_CAN_T_CLK                    	80
#define CONFIG_CAN_USE_DIRECTTRANSFER       	1
#define CONFIG_CAN_TYPE_STM32H743           	1
#define CONFIG_CAN_CONTROLLER_NUMBER        	1
#define CONFIG_CAN_INT_PRIORITY             	1
#define CONFIG_CAN_INT_SUBPRIORITY          	0
#endif /* CO_CONFIG_USE_TARGET_0*/


/*
 * Compiler Setup
 */
#ifdef CO_CONFIG_USE_TARGET_0
#define CONFIG_ALIGNMENT                    	4
#define CONFIG_COMPILER_KEIL_ARMCC          	1
#include <co_keil.h>
#endif /* CO_CONFIG_USE_TARGET_0 */


/* 
 * special DEFINE part - don't edit here, it is changed by
 * the Industrial Communication Creator 
 */
#define CO_CONFIG_SPECIAL_START	1

// Storage Segment Asset Data
#define MEM_SEG_ASSET_DATA			4

#define CO_CONFIG_SPECIAL_END	1



#endif /* CAL_CONF_H */
