/*
 * co_odDefines.h - Object Dictionary Defines
 *
 * Copyright (C) 1998-2026  by port GmbH  Halle/Saale Germany
 *
 *------------------------------------------------------------
 * This file was generated by the Industrial Communication Creator
 * with CANopen feature V7.0.0.202112202107
 * from project C:\Work\Repos\canopenio_stm32h7\src\application\obj_dic\application.iccproj
 * on 2026/05/29 at 10:24:52.
 */

/**
 * \file co_odDefines.h
 * \brief object specific definitions
 *
 * This module contains defines for index numbers of manufacturer-specific
 * and device profile-specific objects.
 * This name of the defines is manufacturer-specific.
 *
 * This module also contains defines for sub-index numbers of
 * manufacturer-specific and device profile-specific objects
 * of object code ARRAY.
 *
 * \author port GmbH  Halle/Saale Germany
 */



#ifndef CO_ODDEFINES_H
#define CO_ODDEFINES_H	1





#endif /* CO_ODDEFINES_H */
