/*
 * objects.h - Object dictionary
 *
 * Copyright (C) 1998-2026  by port GmbH  Halle/Saale Germany
 *
 *------------------------------------------------------------
 * This file was generated by the Industrial Communication Creator
 * with CANopen feature V7.0.0.202112202107
 * from project C:\Work\Repos\canopenio_stm32h7\src\application\obj_dic\application.iccproj
 * on 2026/05/29 at 10:24:52.
 */

/**
 * \file objects.h
 * \brief data type definitions and external declaration for the object dictionary
 *
 * This module contains the object dictionary
 * of the CANopen device.
 *
 * \author port GmbH  Halle/Saale Germany
 */


#ifndef OBJECTS_H
# define OBJECTS_H	1

#include <stdlib.h>
#include <cal_conf.h>      /* !!! first file to include for all CANopen */
#include <co_acces.h>
#include <co_pdo.h>
#include <co_sdo.h>
#include <co_stru.h>
#include <co_stor.h>
#include <string.h>
#include <co_mcpy.h>
/** \struct PDO_MAPPING4_T;
 * \brief PDO mapping structure for 4 mapping entries
 */
typedef struct { 
    UNSIGNED8 numOfEntries;    /**< number of entries */
    UNSIGNED32 map[4];    /**< mapping entries */
} PDO_MAPPING4_T;
 
/** \struct PDO_MAPPING2_T;
 * \brief PDO mapping structure for 2 mapping entries
 */
typedef struct { 
    UNSIGNED8 numOfEntries;    /**< number of entries */
    UNSIGNED32 map[2];    /**< mapping entries */
} PDO_MAPPING2_T;
 
/** \struct PDO_MAPPING1_T;
 * \brief PDO mapping structure for 1 mapping entries
 */
typedef struct { 
    UNSIGNED8 numOfEntries;    /**< number of entries */
    UNSIGNED32 map[1];    /**< mapping entries */
} PDO_MAPPING1_T;
 
/** \struct PDO_MAPPING5_T;
 * \brief PDO mapping structure for 5 mapping entries
 */
typedef struct { 
    UNSIGNED8 numOfEntries;    /**< number of entries */
    UNSIGNED32 map[5];    /**< mapping entries */
} PDO_MAPPING5_T;
 
/** \struct PDO_MAPPING3_T;
 * \brief PDO mapping structure for 3 mapping entries
 */
typedef struct { 
    UNSIGNED8 numOfEntries;    /**< number of entries */
    UNSIGNED32 map[3];    /**< mapping entries */
} PDO_MAPPING3_T;
 

/* Declaration of Variables (Maintenance) */
extern CO_DT_INIT_VAR UNSIGNED16 maxObjDicElements;

/* Declaration of Variables (Device Objects) */

#ifdef CONFIG_EXTERN_COMMUNICATION_PARAMETER
extern CO_DT_INIT_VAR UNSIGNED32 p301_device_type;
extern CO_DT_INIT_VAR UNSIGNED8 p301_error_register;
extern CO_DT_INIT_VAR UNSIGNED32 p301_manu_status_register;
extern CO_DT_INIT_VAR UNSIGNED32 p301_pre_defined_error_field[11];
extern CO_DT_INIT_VAR UNSIGNED32 p301_cob_id_sync;
extern CO_DT_INIT_VAR UNSIGNED32 p301_comm_cycle_period;
extern CO_DT_INIT_VAR VIS_STRING_T p301_manu_device_name[32];
extern CO_DT_INIT_VAR VIS_STRING_T p301_manu_hardware_version[32];
extern CO_DT_INIT_VAR VIS_STRING_T p301_manu_software_version[32];
extern CO_DT_INIT_VAR STORAGE4_T p301_store_para;
extern CO_DT_INIT_VAR STORAGE4_T p301_restore_def_para;
extern CO_DT_INIT_VAR UNSIGNED32 p301_cob_id_emcy;
extern CO_DT_INIT_VAR UNSIGNED16 p301_inhibit_emcy;
extern CO_DT_INIT_VAR UNSIGNED16 p301_prod_hb_time;
extern CO_DT_INIT_VAR IDENTITY_T p301_identity;
extern CO_DT_INIT_VAR PDO_COMM_PAR2_T p301_n1_rpdo_para;
extern CO_DT_INIT_VAR PDO_COMM_PAR2_T p301_n2_rpdo_para;
extern CO_DT_INIT_VAR PDO_COMM_PAR2_T p301_n3_rpdo_para;
extern CO_DT_INIT_VAR PDO_MAPPING4_T p301_n1_rpdo_map;
extern CO_DT_INIT_VAR PDO_MAPPING4_T p301_n2_rpdo_map;
extern CO_DT_INIT_VAR PDO_MAPPING1_T p301_n3_rpdo_map;
extern CO_DT_INIT_VAR PDO_COMM_PAR5_T p301_n1_tpdo_para;
extern CO_DT_INIT_VAR PDO_COMM_PAR5_T p301_n2_tpdo_para;
extern CO_DT_INIT_VAR PDO_COMM_PAR5_T p301_n3_tpdo_para;
extern CO_DT_INIT_VAR PDO_COMM_PAR5_T p301_n4_tpdo_para;
extern CO_DT_INIT_VAR PDO_COMM_PAR5_T p301_n5_tpdo_para;
extern CO_DT_INIT_VAR PDO_COMM_PAR5_T p301_n6_tpdo_para;
extern CO_DT_INIT_VAR PDO_COMM_PAR5_T p301_n7_tpdo_para;
extern CO_DT_INIT_VAR PDO_COMM_PAR5_T p301_n8_tpdo_para;
extern CO_DT_INIT_VAR PDO_COMM_PAR5_T p301_n9_tpdo_para;
extern CO_DT_INIT_VAR PDO_MAPPING5_T p301_n1_tpdo_map;
extern CO_DT_INIT_VAR PDO_MAPPING3_T p301_n2_tpdo_map;
extern CO_DT_INIT_VAR PDO_MAPPING3_T p301_n3_tpdo_map;
extern CO_DT_INIT_VAR PDO_MAPPING1_T p301_n4_tpdo_map;
extern CO_DT_INIT_VAR PDO_MAPPING3_T p301_n5_tpdo_map;
extern CO_DT_INIT_VAR PDO_MAPPING3_T p301_n6_tpdo_map;
extern CO_DT_INIT_VAR PDO_MAPPING2_T p301_n7_tpdo_map;
extern CO_DT_INIT_VAR PDO_MAPPING1_T p301_n8_tpdo_map;
extern CO_DT_INIT_VAR PDO_MAPPING2_T p301_n9_tpdo_map;
extern CO_DT_INIT_VAR UNSIGNED8 p302_program_control[2];
#endif /* CONFIG_EXTERN_COMMUNICATION_PARAMETER */
extern CO_DT_INIT_VAR UNSIGNED32 manDebug[12];
extern CO_DT_INIT_VAR VIS_STRING_T manDeviceName[32];
extern CO_DT_INIT_VAR VIS_STRING_T manHWVersion[32];
extern CO_DT_INIT_VAR VIS_STRING_T manSWVersion[32];
extern CO_DT_INIT_VAR IDENTITY_T co_man_identity;
extern CO_DT_INIT_VAR UNSIGNED8 manCANConfig;
extern CO_DT_INIT_VAR UNSIGNED8 manNodeIDTable[5];
extern CO_DT_INIT_VAR UNSIGNED16 manBaudrateTable[5];
extern CO_DT_INIT_VAR UNSIGNED32 manErrorDesc[5];
extern CO_DT_INIT_VAR UNSIGNED8 manDIWriteValue[6];
extern CO_DT_INIT_VAR UNSIGNED8 manDIWriteMask[6];
extern CO_DT_INIT_VAR UNSIGNED8 manDIFilterTime[41];
extern CO_DT_INIT_VAR UNSIGNED8 manAIFilterTime[21];
extern CO_DT_INIT_VAR UNSIGNED8 manDODefState[5];
extern CO_DT_INIT_VAR UNSIGNED8 manTMP75Config;
extern CO_DT_INIT_VAR INTEGER16 manTPM75Limits[3];
extern CO_DT_INIT_VAR UNSIGNED8 manIsm330DLCData[3];
extern CO_DT_INIT_VAR REAL32 manIsm330DLCQuaternions[5];
extern CO_DT_INIT_VAR REAL32 manIsm330DLCRotations[3];
extern CO_DT_INIT_VAR UNSIGNED8 manIsm330DLCCalibrate[3];
extern CO_DT_INIT_VAR BOOL_T manIsm330DLCOrientConf[4];
extern CO_DT_INIT_VAR UNSIGNED8 manIsm330DLCManualOrientConf[8];
extern CO_DT_INIT_VAR BOOL_T manPWMControl[5];
extern CO_DT_INIT_VAR UNSIGNED32 manPWMFrequency;
extern CO_DT_INIT_VAR UNSIGNED8 manPWMDutyCycle[5];
extern CO_DT_INIT_VAR BOOL_T manPWMErrMode[5];
extern CO_DT_INIT_VAR UNSIGNED8 manPWMErrValue[5];
extern CO_DT_INIT_VAR UNSIGNED8 p410DIRead8Bit[6];
extern CO_DT_INIT_VAR UNSIGNED8 p401DIPolarity8Bit[6];
extern CO_DT_INIT_VAR UNSIGNED8 p401DIFilterConstant8Bit[6];
extern CO_DT_INIT_VAR BOOL_T p401DIInterruptEn;
extern CO_DT_INIT_VAR UNSIGNED8 p401DIMaskAnyChange[6];
extern CO_DT_INIT_VAR UNSIGNED8 p401DIMaskRising[6];
extern CO_DT_INIT_VAR UNSIGNED8 p401DIMaskFalling[6];
extern CO_DT_INIT_VAR UNSIGNED8 p401DOWrite8Bit[5];
extern CO_DT_INIT_VAR UNSIGNED8 p401DOPolarity8Bit[5];
extern CO_DT_INIT_VAR UNSIGNED8 p401DOErrorMode[5];
extern CO_DT_INIT_VAR UNSIGNED8 p401DOErrorVal[5];
extern CO_DT_INIT_VAR UNSIGNED8 p401DOFilterMask[5];
extern CO_DT_INIT_VAR INTEGER16 p401AnalogInput16bit[21];
extern CO_DT_INIT_VAR INTEGER16 p401AnalogOutput16bit[2];
extern CO_DT_INIT_VAR BOOL_T p401AIIRQEnable;
extern CO_DT_INIT_VAR INTEGER32 p401AIIRQUpperLimit[21];
extern CO_DT_INIT_VAR INTEGER32 p401AIIRQLowerLimit[21];
extern CO_DT_INIT_VAR UNSIGNED32 p401AIIRQDelta[21];
extern CO_DT_INIT_VAR UNSIGNED32 p401AIIRQDeltaNeg[21];
extern CO_DT_INIT_VAR UNSIGNED32 p401AIIRQDeltaPos[21];
extern CO_DT_INIT_VAR INTEGER32 p401AIOffset[21];
extern CO_DT_INIT_VAR INTEGER32 p401AIPrescale[21];
extern CO_DT_INIT_VAR UNSIGNED8 p401AOErrorMode[2];
extern CO_DT_INIT_VAR INTEGER32 p401AOErrorValue[2];
extern CO_DT_INIT_VAR INTEGER32 p401AOOffset[2];
extern CO_DT_INIT_VAR INTEGER32 p401AOScaling[2];


/* Declaration of Value Descriptions */

#ifdef CONFIG_EXTERN_VALUE_DESCRIPTION
extern CO_CONST VALUE_DESC_T i1000_desc[1];
extern CO_CONST VALUE_DESC_T i1001_desc[1];
extern CO_CONST VALUE_DESC_T i1002_desc[1];
extern CO_CONST VALUE_DESC_T i1003_desc[11];
extern CO_CONST VALUE_DESC_T i1005_desc[1];
extern CO_CONST VALUE_DESC_T i1006_desc[1];
extern CO_CONST VALUE_DESC_T i1008_desc[1];
extern CO_CONST VALUE_DESC_T i1009_desc[1];
extern CO_CONST VALUE_DESC_T i100A_desc[1];
extern CO_CONST VALUE_DESC_T i1010_desc[5];
extern CO_CONST VALUE_DESC_T i1011_desc[5];
extern CO_CONST VALUE_DESC_T i1014_desc[1];
extern CO_CONST VALUE_DESC_T i1015_desc[1];
extern CO_CONST VALUE_DESC_T i1017_desc[1];
extern CO_CONST VALUE_DESC_T i1018_desc[5];
extern CO_CONST VALUE_DESC_T i1400_desc[3];
extern CO_CONST VALUE_DESC_T i1401_desc[3];
extern CO_CONST VALUE_DESC_T i1402_desc[3];
extern CO_CONST VALUE_DESC_T i1600_desc[5];
extern CO_CONST VALUE_DESC_T i1601_desc[5];
extern CO_CONST VALUE_DESC_T i1602_desc[2];
extern CO_CONST VALUE_DESC_T i1800_desc[6];
extern CO_CONST VALUE_DESC_T i1801_desc[6];
extern CO_CONST VALUE_DESC_T i1802_desc[6];
extern CO_CONST VALUE_DESC_T i1803_desc[6];
extern CO_CONST VALUE_DESC_T i1804_desc[6];
extern CO_CONST VALUE_DESC_T i1805_desc[6];
extern CO_CONST VALUE_DESC_T i1806_desc[6];
extern CO_CONST VALUE_DESC_T i1807_desc[6];
extern CO_CONST VALUE_DESC_T i1808_desc[6];
extern CO_CONST VALUE_DESC_T i1A00_desc[6];
extern CO_CONST VALUE_DESC_T i1A01_desc[4];
extern CO_CONST VALUE_DESC_T i1A02_desc[4];
extern CO_CONST VALUE_DESC_T i1A03_desc[2];
extern CO_CONST VALUE_DESC_T i1A04_desc[4];
extern CO_CONST VALUE_DESC_T i1A05_desc[4];
extern CO_CONST VALUE_DESC_T i1A06_desc[3];
extern CO_CONST VALUE_DESC_T i1A07_desc[2];
extern CO_CONST VALUE_DESC_T i1A08_desc[3];
extern CO_CONST VALUE_DESC_T i1F51_desc[2];
extern CO_CONST VALUE_DESC_T i2000_desc[12];
extern CO_CONST VALUE_DESC_T i2008_desc[1];
extern CO_CONST VALUE_DESC_T i2009_desc[1];
extern CO_CONST VALUE_DESC_T i200A_desc[1];
extern CO_CONST VALUE_DESC_T i2018_desc[5];
extern CO_CONST VALUE_DESC_T i2019_desc[2];
extern CO_CONST VALUE_DESC_T i201A_desc[1];
extern CO_CONST VALUE_DESC_T i2100_desc[1];
extern CO_CONST VALUE_DESC_T i2101_desc[5];
extern CO_CONST VALUE_DESC_T i2102_desc[5];
extern CO_CONST VALUE_DESC_T i2200_desc[5];
extern CO_CONST VALUE_DESC_T i5001_desc[6];
extern CO_CONST VALUE_DESC_T i5002_desc[6];
extern CO_CONST VALUE_DESC_T i5003_desc[41];
extern CO_CONST VALUE_DESC_T i5004_desc[21];
extern CO_CONST VALUE_DESC_T i5006_desc[5];
extern CO_CONST VALUE_DESC_T i5101_desc[1];
extern CO_CONST VALUE_DESC_T i5102_desc[3];
extern CO_CONST VALUE_DESC_T i5200_desc[3];
extern CO_CONST VALUE_DESC_T i5300_desc[5];
extern CO_CONST VALUE_DESC_T i5301_desc[3];
extern CO_CONST VALUE_DESC_T i5302_desc[3];
extern CO_CONST VALUE_DESC_T i5303_desc[4];
extern CO_CONST VALUE_DESC_T i5304_desc[8];
extern CO_CONST VALUE_DESC_T i5401_desc[5];
extern CO_CONST VALUE_DESC_T i5402_desc[1];
extern CO_CONST VALUE_DESC_T i5403_desc[5];
extern CO_CONST VALUE_DESC_T i5404_desc[5];
extern CO_CONST VALUE_DESC_T i5405_desc[5];
extern CO_CONST VALUE_DESC_T i6000_desc[6];
extern CO_CONST VALUE_DESC_T i6002_desc[6];
extern CO_CONST VALUE_DESC_T i6003_desc[6];
extern CO_CONST VALUE_DESC_T i6005_desc[1];
extern CO_CONST VALUE_DESC_T i6006_desc[6];
extern CO_CONST VALUE_DESC_T i6007_desc[6];
extern CO_CONST VALUE_DESC_T i6008_desc[6];
extern CO_CONST VALUE_DESC_T i6200_desc[5];
extern CO_CONST VALUE_DESC_T i6202_desc[5];
extern CO_CONST VALUE_DESC_T i6206_desc[5];
extern CO_CONST VALUE_DESC_T i6207_desc[5];
extern CO_CONST VALUE_DESC_T i6208_desc[5];
extern CO_CONST VALUE_DESC_T i6401_desc[21];
extern CO_CONST VALUE_DESC_T i6411_desc[2];
extern CO_CONST VALUE_DESC_T i6423_desc[1];
extern CO_CONST VALUE_DESC_T i6424_desc[21];
extern CO_CONST VALUE_DESC_T i6425_desc[21];
extern CO_CONST VALUE_DESC_T i6426_desc[21];
extern CO_CONST VALUE_DESC_T i6427_desc[21];
extern CO_CONST VALUE_DESC_T i6428_desc[21];
extern CO_CONST VALUE_DESC_T i6431_desc[21];
extern CO_CONST VALUE_DESC_T i6432_desc[21];
extern CO_CONST VALUE_DESC_T i6443_desc[2];
extern CO_CONST VALUE_DESC_T i6444_desc[2];
extern CO_CONST VALUE_DESC_T i6446_desc[2];
extern CO_CONST VALUE_DESC_T i6447_desc[2];
#endif /* CONFIG_EXTERN_VALUE_DESCRIPTION */

/* Declaration of Object Dictionary */
#ifdef CONFIG_EXTERN_COMMUNICATION_PARAMETER
extern OBJDIR_T objDir[];
#endif /* CONFIG_EXTERN_COMMUNICATION_PARAMETER */
#endif /* OBJECTS_H*/


/*----------------------------------------------------------------------------*/

