/*
 * objects.h - Object dictionary
 *
 * Copyright (C) 1998-2026  by port GmbH  Halle/Saale Germany
 *
 *------------------------------------------------------------
 * This file was generated by the Industrial Communication Creator
 * with CANopen feature V7.0.0.202112202107
 * from project C:\Work\Repos\canopenio_stm32h7\src\bootloader\obj_dic\bootloader.iccproj
 * on 2026/04/23 at 17:03:23.
 */

/**
 * \file objects.h
 * \brief data type definitions and external declaration for the object dictionary
 *
 * This module contains the object dictionary
 * of the CANopen device.
 *
 * \author port GmbH  Halle/Saale Germany
 */


#ifndef OBJECTS_H
# define OBJECTS_H	1

#include <stdlib.h>
#include <cal_conf.h>      /* !!! first file to include for all CANopen */
#include <co_acces.h>
#include <co_pdo.h>
#include <co_sdo.h>
#include <co_stru.h>
#include <co_stor.h>
#include <string.h>
#include <co_mcpy.h>
/** \struct DOMAIN_FIELD_1_T;
 * \brief domain storage structure with 1 entries
 */
typedef struct {
    UNSIGNED8 numOfEntries;    /**< number of entries */
    DOMAIN_T targetAdr[1];    /**< domain target address field*/
} DOMAIN_FIELD1_T;


/* Declaration of Variables (Maintenance) */
extern CO_DT_INIT_VAR UNSIGNED16 maxObjDicElements;

/* Declaration of Variables (Device Objects) */

#ifdef CONFIG_EXTERN_COMMUNICATION_PARAMETER
extern CO_DT_INIT_VAR UNSIGNED32 p301_device_type;
extern CO_DT_INIT_VAR UNSIGNED8 p301_error_register;
extern CO_DT_INIT_VAR UNSIGNED32 p301_manu_status_register;
extern CO_DT_INIT_VAR VIS_STRING_T p301_manu_device_name[32];
extern CO_DT_INIT_VAR VIS_STRING_T p301_manu_hardware_version[32];
extern CO_DT_INIT_VAR VIS_STRING_T p301_manu_software_version[32];
extern CO_DT_INIT_VAR STORAGE4_T p301_store_para;
extern CO_DT_INIT_VAR STORAGE4_T p301_restore_def_para;
extern CO_DT_INIT_VAR UNSIGNED32 p301_cob_id_emcy;
extern CO_DT_INIT_VAR UNSIGNED16 p301_inhibit_emcy;
extern CO_DT_INIT_VAR UNSIGNED16 p301_prod_hb_time;
extern CO_DT_INIT_VAR IDENTITY_T p301_identity;
extern CO_DT_INIT_VAR DOMAIN_FIELD1_T p302_dnld_program_data;
extern CO_DT_INIT_VAR UNSIGNED8 p302_program_control[2];
#endif /* CONFIG_EXTERN_COMMUNICATION_PARAMETER */
extern CO_DT_INIT_VAR VIS_STRING_T manDeviceName[32];
extern CO_DT_INIT_VAR VIS_STRING_T manHWVersion[32];
extern CO_DT_INIT_VAR IDENTITY_T manIdentityObject;
extern CO_DT_INIT_VAR UNSIGNED8 manCANConfig;
extern CO_DT_INIT_VAR UNSIGNED8 manNodeIDTable[5];
extern CO_DT_INIT_VAR UNSIGNED16 manBaudrateTable[5];
extern CO_DT_INIT_VAR UNSIGNED32 manErrorDesc[5];


/* Declaration of Value Descriptions */

#ifdef CONFIG_EXTERN_VALUE_DESCRIPTION
extern CO_CONST VALUE_DESC_T i1000_desc[1];
extern CO_CONST VALUE_DESC_T i1001_desc[1];
extern CO_CONST VALUE_DESC_T i1002_desc[1];
extern CO_CONST VALUE_DESC_T i1008_desc[1];
extern CO_CONST VALUE_DESC_T i1009_desc[1];
extern CO_CONST VALUE_DESC_T i100A_desc[1];
extern CO_CONST VALUE_DESC_T i1010_desc[5];
extern CO_CONST VALUE_DESC_T i1011_desc[5];
extern CO_CONST VALUE_DESC_T i1014_desc[1];
extern CO_CONST VALUE_DESC_T i1015_desc[1];
extern CO_CONST VALUE_DESC_T i1017_desc[1];
extern CO_CONST VALUE_DESC_T i1018_desc[5];
extern CO_CONST VALUE_DESC_T i1F50_desc[2];
extern CO_CONST VALUE_DESC_T i1F51_desc[2];
extern CO_CONST VALUE_DESC_T i2008_desc[1];
extern CO_CONST VALUE_DESC_T i2009_desc[1];
extern CO_CONST VALUE_DESC_T i2018_desc[5];
extern CO_CONST VALUE_DESC_T i2100_desc[1];
extern CO_CONST VALUE_DESC_T i2101_desc[5];
extern CO_CONST VALUE_DESC_T i2102_desc[5];
extern CO_CONST VALUE_DESC_T i2200_desc[5];
#endif /* CONFIG_EXTERN_VALUE_DESCRIPTION */

/* Declaration of Object Dictionary */
#ifdef CONFIG_EXTERN_COMMUNICATION_PARAMETER
extern OBJDIR_T objDir[];
#endif /* CONFIG_EXTERN_COMMUNICATION_PARAMETER */
#endif /* OBJECTS_H*/


/*----------------------------------------------------------------------------*/

