/*
 * objects.c - Object dictionary
 *
 * Copyright (C) 1998-2026  by port GmbH  Halle/Saale Germany
 *
 *------------------------------------------------------------
 * This file was generated by the Industrial Communication Creator
 * with CANopen feature V7.0.0.202112202107
 * from project C:\Work\Repos\canopenio_stm32h7\src\bootloader\obj_dic\bootloader.iccproj
 * on 2026/04/23 at 17:03:23.
 */

/**
 * \file objects.c
 * \brief object dictionary
 *
 * This module contains the object dictionary
 * of the CANopen device.
 *
 * \author port GmbH  Halle/Saale Germany
 */


# define OBJECTS_C	1

#include <stdlib.h>
#include <cal_conf.h>      /* !!! first file to include for all CANopen */
#include <objects.h>
/*  number of entries in the object dictionary */
CO_DT_INIT_VAR UNSIGNED16 maxObjDicElements = 21;
/*  Definition of Variables (Device Objects)  */
CO_DT_INIT_VAR UNSIGNED32 p301_device_type = {0x00070191UL};
CO_DT_INIT_VAR UNSIGNED8 p301_error_register = {0x00};
CO_DT_INIT_VAR UNSIGNED32 p301_manu_status_register = {0x00000000UL};
CO_DT_INIT_VAR VIS_STRING_T p301_manu_device_name[32] = {"CANIO_EXT"};
CO_DT_INIT_VAR VIS_STRING_T p301_manu_hardware_version[32] = {"B02"};
CO_DT_INIT_VAR VIS_STRING_T p301_manu_software_version[32] = {"0.0.1 Bootloader"};
CO_DT_INIT_VAR STORAGE4_T p301_store_para = {0x04UL, {0x00000001UL, 0x00000001UL, 0x00000001UL, 0x00000001UL}};
CO_DT_INIT_VAR STORAGE4_T p301_restore_def_para = {0x04UL, {0x00000001UL, 0x00000001UL, 0x00000001UL, 0x00000001UL}};
CO_DT_INIT_VAR UNSIGNED32 p301_cob_id_emcy = {0x00000080UL};
CO_DT_INIT_VAR UNSIGNED16 p301_inhibit_emcy = {0x0000};
CO_DT_INIT_VAR UNSIGNED16 p301_prod_hb_time = {0x03E8};
CO_DT_INIT_VAR IDENTITY_T p301_identity = {0x04, 0x00500053UL, 0x00B5F946UL, 0x00000000UL, 0x0007A12EUL};
CO_DT_INIT_VAR DOMAIN_FIELD1_T p302_dnld_program_data = {0x01, {NULL}};
CO_DT_INIT_VAR UNSIGNED8 p302_program_control[2] = {0x01, 0x00};
CO_DT_INIT_VAR VIS_STRING_T manDeviceName[32] = {"CANIO_EXT"};
CO_DT_INIT_VAR VIS_STRING_T manHWVersion[32] = {"B02"};
CO_DT_INIT_VAR IDENTITY_T manIdentityObject = {0x04, 0x00500053UL, 0x00B5F946UL, 0x00000000UL, 0x0007A12EUL};
CO_DT_INIT_VAR UNSIGNED8 manCANConfig = {0x00};
CO_DT_INIT_VAR UNSIGNED8 manNodeIDTable[5] = {0x04, 0x34, 0x34, 0x34, 0x34};
CO_DT_INIT_VAR UNSIGNED16 manBaudrateTable[5] = {0x04, 0x01F4, 0x01F4, 0x01F4, 0x01F4};
CO_DT_INIT_VAR UNSIGNED32 manErrorDesc[5] = {0x04UL, 0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000000UL};


/* Default values */
CO_DT_INIT_VAR UNSIGNED8 l0_default0_0005[1] = {0x1};
CO_DT_INIT_VAR DOMAIN_DATA_T l0_domain_data_0[1] = {{0x0}};
CO_CONST UNSIGNED8 l0_default1_0005[4] = {0x0, 0x4, 0x1, 0x34};
CO_CONST UNSIGNED16 l0_default1_0006[4] = {0x0, 0x3E8, 0x4, 0x1F4};
CO_CONST UNSIGNED32 l0_default1_0007[6] = {0x70191UL, 0x0UL, 0x1UL, 0x80UL, 0x500053UL, 0x4UL};
CO_CONST STRING_DATA_T l0_string_data_1[5] = {{0x20, 0x20}, {0x20, 0x20}, {0x20, 0x20}, {0x20, 0x20}, {0x20, 0x20}};


/* Limits */
#ifdef CONFIG_LIMITS_CHECK
CO_DT_INIT_VAR LIMIT_U8_T l0_limits0_0005[1] = {{0x1, 0xFE}};
CO_CONST LIMIT_U8_T l0_limits1_0005[4] = {{0x0, 0xFF}, {0x0, 0x7F}, {0x1, 0x4}, {0x1, 0xFF}};
CO_CONST LIMIT_U16_T l0_limits1_0006[2] = {{0x0, 0xFFFF}, {0x0, 0xFF}};
CO_CONST LIMIT_U32_T l0_limits1_0007[3] = {{0x0UL, 0xFFFFFFFFUL}, {0x80UL, 0xBFFFFFFFUL}, {0x0UL, 0xFFUL}};
#endif /* CONFIG_LIMITS_CHECK */


/*  Definition of Value Descriptions  */
CO_CONST VALUE_DESC_T i1000_desc[1] = {
    { (UNSIGNED8 *)&l0_default1_0007[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL }
    };

CO_CONST VALUE_DESC_T i1001_desc[1] = {
    { (UNSIGNED8 *)&l0_default1_0005[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0005[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED8, CO_READ_PERM | CO_NUM_VAL }
    };

CO_CONST VALUE_DESC_T i1002_desc[1] = {
    { (UNSIGNED8 *)&l0_default1_0007[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL }
    };

CO_CONST VALUE_DESC_T i1008_desc[1] = {
    { (UNSIGNED8 *)&l0_string_data_1[0],
#ifdef CONFIG_LIMITS_CHECK
    NULL,
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_VISSTRING, CO_READ_PERM | CO_CONST_PERM }
    };

CO_CONST VALUE_DESC_T i1009_desc[1] = {
    { (UNSIGNED8 *)&l0_string_data_1[1],
#ifdef CONFIG_LIMITS_CHECK
    NULL,
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_VISSTRING, CO_READ_PERM | CO_CONST_PERM }
    };

CO_CONST VALUE_DESC_T i100A_desc[1] = {
    { (UNSIGNED8 *)&l0_string_data_1[2],
#ifdef CONFIG_LIMITS_CHECK
    NULL,
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_VISSTRING, CO_READ_PERM | CO_CONST_PERM }
    };

CO_CONST VALUE_DESC_T i1010_desc[5] = {
    { (UNSIGNED8 *)&l0_default1_0007[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[1],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_CONST_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[2],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[2],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[2],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[2],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL }
    };

CO_CONST VALUE_DESC_T i1011_desc[5] = {
    { (UNSIGNED8 *)&l0_default1_0007[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[1],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_CONST_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[2],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[2],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[2],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[2],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL }
    };

CO_CONST VALUE_DESC_T i1014_desc[1] = {
    { (UNSIGNED8 *)&l0_default1_0007[3],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[1],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL }
    };

CO_CONST VALUE_DESC_T i1015_desc[1] = {
    { (UNSIGNED8 *)&l0_default1_0006[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0006[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED16, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL }
    };

CO_CONST VALUE_DESC_T i1017_desc[1] = {
    { (UNSIGNED8 *)&l0_default1_0006[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0006[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED16, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL }
    };

CO_CONST VALUE_DESC_T i1018_desc[5] = {
    { (UNSIGNED8 *)&l0_default1_0005[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0005[2],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED8, CO_READ_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[4],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL }
    };

CO_CONST VALUE_DESC_T i1F50_desc[2] = {
    { (UNSIGNED8 *)&l0_default0_0005[0],
#ifdef CONFIG_LIMITS_CHECK
    NULL,
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED8, CO_READ_PERM | CO_CONST_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_domain_data_0[0],
#ifdef CONFIG_LIMITS_CHECK
    NULL,
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_DOMAIN, CO_READ_PERM | CO_WRITE_PERM | CO_UP_DN_LD_DOMAIN }
    };

CO_CONST VALUE_DESC_T i1F51_desc[2] = {
    { (UNSIGNED8 *)&l0_default1_0005[2],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0005[3],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED8, CO_READ_PERM | CO_CONST_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0005[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0005[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED8, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL }
    };

CO_CONST VALUE_DESC_T i2008_desc[1] = {
    { (UNSIGNED8 *)&l0_string_data_1[3],
#ifdef CONFIG_LIMITS_CHECK
    NULL,
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_VISSTRING, CO_READ_PERM | CO_WRITE_PERM | CO_OBJ_ATTR_SAVE }
    };

CO_CONST VALUE_DESC_T i2009_desc[1] = {
    { (UNSIGNED8 *)&l0_string_data_1[4],
#ifdef CONFIG_LIMITS_CHECK
    NULL,
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_VISSTRING, CO_READ_PERM | CO_WRITE_PERM | CO_OBJ_ATTR_SAVE }
    };

CO_CONST VALUE_DESC_T i2018_desc[5] = {
    { (UNSIGNED8 *)&l0_default1_0005[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0005[2],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED8, CO_READ_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[4],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL | CO_OBJ_ATTR_SAVE },
    { (UNSIGNED8 *)&l0_default1_0007[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL | CO_OBJ_ATTR_SAVE },
    { (UNSIGNED8 *)&l0_default1_0007[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL | CO_OBJ_ATTR_SAVE }
    };

CO_CONST VALUE_DESC_T i2100_desc[1] = {
    { (UNSIGNED8 *)&l0_default1_0005[0],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0005[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED8, CO_READ_PERM | CO_NUM_VAL }
    };

CO_CONST VALUE_DESC_T i2101_desc[5] = {
    { (UNSIGNED8 *)&l0_default1_0005[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0005[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED8, CO_READ_PERM | CO_CONST_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0005[3],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0005[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED8, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL | CO_OBJ_ATTR_SAVE },
    { (UNSIGNED8 *)&l0_default1_0005[3],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0005[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED8, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL | CO_OBJ_ATTR_SAVE },
    { (UNSIGNED8 *)&l0_default1_0005[3],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0005[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED8, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL | CO_OBJ_ATTR_SAVE },
    { (UNSIGNED8 *)&l0_default1_0005[3],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0005[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED8, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL | CO_OBJ_ATTR_SAVE }
    };

CO_CONST VALUE_DESC_T i2102_desc[5] = {
    { (UNSIGNED8 *)&l0_default1_0006[2],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0006[1],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED16, CO_READ_PERM | CO_CONST_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0006[3],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0006[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED16, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL | CO_OBJ_ATTR_SAVE },
    { (UNSIGNED8 *)&l0_default1_0006[3],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0006[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED16, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL | CO_OBJ_ATTR_SAVE },
    { (UNSIGNED8 *)&l0_default1_0006[3],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0006[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED16, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL | CO_OBJ_ATTR_SAVE },
    { (UNSIGNED8 *)&l0_default1_0006[3],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0006[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED16, CO_READ_PERM | CO_WRITE_PERM | CO_NUM_VAL | CO_OBJ_ATTR_SAVE }
    };

CO_CONST VALUE_DESC_T i2200_desc[5] = {
    { (UNSIGNED8 *)&l0_default1_0007[5],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[2],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_CONST_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL },
    { (UNSIGNED8 *)&l0_default1_0007[1],
#ifdef CONFIG_LIMITS_CHECK
    (LIMIT_U8_T *) &l0_limits1_0007[0],
#endif /* CONFIG_LIMITS_CHECK */
    CO_TYPEDESC_UNSIGNED32, CO_READ_PERM | CO_NUM_VAL }
    };

/* Definition of the object directory */
OBJDIR_T objDir[] = {
{   (UNSIGNED8 *)&p301_device_type,
    (VALUE_DESC_T *)i1000_desc,
    0x1000, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)&p301_error_register,
    (VALUE_DESC_T *)i1001_desc,
    0x1001, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)&p301_manu_status_register,
    (VALUE_DESC_T *)i1002_desc,
    0x1002, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)p301_manu_device_name,
    (VALUE_DESC_T *)i1008_desc,
    0x1008, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)p301_manu_hardware_version,
    (VALUE_DESC_T *)i1009_desc,
    0x1009, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)p301_manu_software_version,
    (VALUE_DESC_T *)i100A_desc,
    0x100A, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)&p301_store_para,
    (VALUE_DESC_T *)i1010_desc,
    0x1010, 5 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)&p301_restore_def_para,
    (VALUE_DESC_T *)i1011_desc,
    0x1011, 5 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)&p301_cob_id_emcy,
    (VALUE_DESC_T *)i1014_desc,
    0x1014, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)&p301_inhibit_emcy,
    (VALUE_DESC_T *)i1015_desc,
    0x1015, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)&p301_prod_hb_time,
    (VALUE_DESC_T *)i1017_desc,
    0x1017, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)&p301_identity,
    (VALUE_DESC_T *)i1018_desc,
    0x1018, 5 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)&p302_dnld_program_data,
    (VALUE_DESC_T *)i1F50_desc,
    0x1F50, 2 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)p302_program_control,
    (VALUE_DESC_T *)i1F51_desc,
    0x1F51, 2 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)manDeviceName,
    (VALUE_DESC_T *)i2008_desc,
    0x2008, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)manHWVersion,
    (VALUE_DESC_T *)i2009_desc,
    0x2009, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)&manIdentityObject,
    (VALUE_DESC_T *)i2018_desc,
    0x2018, 5 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)&manCANConfig,
    (VALUE_DESC_T *)i2100_desc,
    0x2100, 1 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)manNodeIDTable,
    (VALUE_DESC_T *)i2101_desc,
    0x2101, 5 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)manBaudrateTable,
    (VALUE_DESC_T *)i2102_desc,
    0x2102, 5 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    },

{   (UNSIGNED8 *)manErrorDesc,
    (VALUE_DESC_T *)i2200_desc,
    0x2200, 5 
#ifdef CO_CONFIG_ENABLE_OBJ_CALLBACK
    , NULL
#endif /* CO_CONFIG_ENABLE_OBJ_CALLBACK */
    }

};

